### ISSUE TITLE
Support for private repositories

### ISSUE THREAD

**Issue by totycro** [atlwendy/retrieve-commit-messages-from-pr#2]
Hi,

I just realized that this extension doesn't work for private repositories because cloning fails. It should be possible to add support for this when passing in a `GITHUB_TOKEN` similar to e.g. this extension: https://github.com/unsplash/comment-on-pr

Cloning the repo could then use the token like tihs:
`git clone https://<token>@github.com/owner/repo.git`
https://github.blog/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/

**Comment by atlwendy** [comment]
👍 thank you @totycro! I was only testing against open source projects. 
Will add this and push out another release.

**Comment by atlwendy** [comment]
@totycro new release has been pushed out. It turns out `GITHUB_TOKEN` cannot be used for cloning private repo. You'd need to provide access token which you can generate from github. Saving that in your secrets. Please let me know whether that works for you.

**Comment by totycro** [comment]
The new version looks great! I have to admit though that by now I switched to a different workflow, so right now I'm not actively using this action. But it would cover my use case and I'll keep it in mind for the future!
